project:
  type: book

book:
  title: "Meta-analyses & Systematic reviews"
  
  author: 
    - name: "Damien Beillouin"
      orcid: "0000-0003-2014-3482"
      url: "https://www.researchgate.net/profile/Damien-Beillouin"
      affiliations: 
        - name: Cirad HortSys
          url: "https://ur-hortsys.cirad.fr/"
    - name: "Joseph Langridge"
      orcid: 0000-0002-9427-439X
      url: https://www.researchgate.net/profile/Joseph-Langridge
      affiliations:
        - name: FRB-CESAB
          url: https://www.fondationbiodiversite.fr/la-fondation/le-cesab/
    - name: "Nicolas Casajus"
      url: https://nicolascasajus.fr
      affiliations: 
        - name: FRB-CESAB
          url: https://www.fondationbiodiversite.fr/la-fondation/le-cesab/
      orcid: 0000-0002-5537-5294
    - name: "C. Sylvie Campagne"
      orcid: 0000-0002-2566-7827
      url: https://csylviecampagne.com/
      affiliations: 
        - name: Sorbonne University
          url: https://www.sorbonne-universite.fr/
    - name: "Dakis-Yaoba Ouédraogo"
      orcid: 0000-0003-2674-2259
      url: https://www.researchgate.net/profile/Dakis-Yaoba-Ouedraogo-2
      affiliations: 
        - name: Independent expert
          url: "#"
          
  date: today
  description: |
    A notebook derived from the FRB-CESAB, PatriNat & Cirad Hortsys training course
    <br /><br />
    <a href="https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/develop-skills/biodiversity-knowledge-synthesis-an-introduction-to-meta-analyses-and-systematic-reviews/">
      <img class="logo" src="https://raw.githubusercontent.com/literaturesynthesis/.github/main/profile/banner-literaturesynthesis_150dpi.png" style="width: 100%;" />
    </a>

  favicon: images/favicon.png
  
  sidebar: 
    style: "docked"
    collapse-level: 1

  page-footer: 
    left: "License [CC BY 4.0](https://github.com/literaturesynthesis/notebook)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/literaturesynthesis/notebook/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
  
  reader-mode: false
  search: false
  
  chapters:
    - index.qmd
    - part: "Evidence map"
      chapters:
        - chapters/introduction.qmd
        - chapters/temporal-analyses.qmd
        - chapters/resources.qmd
    
format:
  html:
    theme: [cosmo, styles/main.scss]
    code-copy: true
    code-line-numbers: false

knitr:
  opts_chunk: 
    comment: "##"
    echo: true
    eval: true
    warning: false
    message: false
    dpi: 150
    out-width: "80%"
    fig-align: "center"
